### ISSUE TITLE
Client -> Rinkeby: Consensus Error on Block 14182 (invalid receiptTrie)

### ISSUE THREAD

**Issue by holgerd77** [ethereumjs/ethereumjs-monorepo#1090]
At least we made it up to block 14182 after the fixes from #1089 - that's something. To relativize a bit, there were only 10 or so transactions along the way. 😂  😂  😂

This one is significantly more complex, here is the output:

![image](https://user-images.githubusercontent.com/931137/107617074-84227900-6c4f-11eb-81e5-10cf9837f771.png)

![image](https://user-images.githubusercontent.com/931137/107617141-9ef4ed80-6c4f-11eb-8acc-82fee56745fd.png)

Block on Rinkeby: [14182](https://rinkeby.etherscan.io/block/14182)

Some first observations and thoughts:

- Shouldn't be related to #1076, since this one here is on `SpuriousDragon` and #1076 is fixing a pre-Homestead bug (that said, @jochem-brouwer you mentioned that you need to fix other bugs. Have these already been fixed and are these independent from the Homestead HF and might play a role here?)
- I have to say that this early breaking on PoA puzzles me since mainnet was running so smoothly for such a long period of blocks: this might be an indicator that this has something to do with the PoA implementation as well, can't think of anything atm though
- Gas used matches (with `1339314`), being an indicator that there is likely nothing wrong along opcode execution I guess? 🤔

Ok. We'll see. 😄  😋

**Comment by jochem-brouwer** [comment]
Hi @holgerd77, first of all these debug messages look great!

The problem in #1076 is that this particular transaction seems to trigger multiple, possibly unrelated bugs. The problem is there that a wrong value is written to a storage slot. Therefore the state root is wrong after execution. It might be that the bug here is also caused by that bug, it could be a bug in an opcode which has not changed during Frontier -> SpuriousDragon.

**Comment by holgerd77** [comment]
@jochem-brouwer thanks for the quick response - yeah- always difficult to spot. I then still wonder though why such generic bugs have not been triggered on mainnet with this load of transactions? 🤔  This might be an indicator that wrong behavior is either a) PoA change or b) HF related (since on mainnet we are still running everything on `Frontier`).

But of course might also be some incidence and a very early transaction has triggered the same bug (probability nevertheless points in the other direction I guess).

(argh, I have got a signifcant problem with my "b" on the keyboard, really annoying 😜 )

**Comment by holgerd77** [comment]
One high-level thing I noticed here: even if the `receiptTrie` check is failing seeing from the debug output the block state is actually committed, see code in [VM.runBlock()](https://github.com/ethereumjs/ethereumjs-monorepo/blob/master/packages/vm/lib/runBlock.ts#L200) for context. I am not sure if this behavior hasn't already compromised our state DBs on debugging, normally this *SHOULD* be the case by the state DB being in an after-blog-state after first run? 🤔

I would very much think this is not what we (anyone) want and these checks should be rather done *BEFORE*  the commit and in case of - actually all checks except for the `stateRoot` - so for `receiptTrie`, `bloom` and `gasUsed`.

For `stateRoot` would it eventually work if we do a double-commit (now with our super-fast checkpointing 😋 ) and do two `checkpoint` calls before - one `commit` (which should commit towards checkpoint 2) after - then do the checks and in case of a failure revert with a `revert` to checkpoint 1. Is our MPT library prepared for that level of nesting?

**Comment by holgerd77** [comment]
(please read on site, several corrections)

**Comment by jochem-brouwer** [comment]
I don't think it compromises the state. Keep in mind that we set the state root to the root of the previous block before using it. Since we never delete any trie nodes, we can successfully find the right data. 

If this would not be the case, then I would not be able to succesfully execute the mainnet block in #1081. If the block would fail (as it did in client) and it would compromise the database, then I would not be able to execute the block after I've fixed it (I should then re-run the client).

As a side node; this also means that we are currently always running in archive node, since the trie is never pruned.

**Comment by holgerd77** [comment]
TBH I never really got this "one is resetting the state root and everything works magically" concept - this is one of my large blind spots. Why are no state root entries overwritten in between - e.g. by these tx commits? 🤔  I am repeatedly not getting this when seeing this pattern (set stateRoot -> everything correct).

**Comment by jochem-brouwer** [comment]
The state root is essentially the hash of the entire database. Consider what would happen if, at any point, we would delete trie nodes if they are updated. For instance, if we have a branch node, and one of the keys has a certain hash A, then. when the trie nodes further down the trie are updated, then hash A changes. We can thus delete the hash A from the database. Consider that we do this approach after every block. This is problematic if there's a reorg; we would then have deleted trie node items which we would need if we have to reset the database to an older state root.

Also consider what would happen if we do that by tx commits; if in the end the block turns out to be bad, we have overwritten the old trie and have to do a full re-sync. We also cannot do this directly when we commit inner messages in a transaction, since a transaction at lower depth (say the root transaction) might revert / run out of gas, so then we have to revert our trie also (which we cannot do if we miss nodes).

I don't know how Geth does this, I think they persist state for like a rather large amount of blocks, and there is an extra sweeper process which sometimes deletes state roots if they are old (when we are in full mode, not archive).

**Comment by jochem-brouwer** [comment]
Hi, I just noticed that gas usage actually does not match. The numbers look the same but they are not; there is a difference of 600 gas. Taking a further look here.

**Comment by holgerd77** [comment]
> The numbers look the same but they are not

That's also a funny statement. 😄  Nice spot!

**Comment by jochem-brouwer** [comment]
Kind of funny how such a gigantic transaction triggers the bug, if there would just be a small transaction with any of the tangerine whistle gas-change operations then we would have found this bug much faster 😂
