### ISSUE TITLE
Usage example is non-functional in node 14

### ISSUE THREAD

**Issue by TimDaub** [ethereumjs/ethereumjs-monorepo#1131]
```bash
$ node --version
v14.16.0
```

I copy [the usage example](https://github.com/ethereumjs/ethereumjs-monorepo/tree/master/packages/vm#usage) into an `.mjs` (ESM) file and try to run it:

```bash
$ node index.mjs
file:///Users/user/Projects/evm-test/index.mjs:5
const common = new Common({ chain: 'mainnet' })
               ^

TypeError: Common is not a constructor
    at file:///Users/user/Projects/evm-test/index.mjs:5:16
    at ModuleJob.run (internal/modules/esm/module_job.js:152:23)
    at async Loader.import (internal/modules/esm/loader.js:166:24)
    at async Object.loadESM (internal/process/esm_loader.js:68:5)
```

Why do I run it as an ESM module?
Because from the example's usage of "import ... from..." I assumed that it uses this syntax. 
How is it supposed to be run? I may be able to send a fix.

**Comment by jochem-brouwer** [comment]
Hey there, thanks for opening this issue! 😄 

What happens if you run this in ts-node?

**Comment by TimDaub** [comment]
> What happens if you run this in ts-node?

```
$ ts-node index.ts
Opcode: PUSH1   Stack:
Opcode: PUSH1   Stack: 3
Opcode: ADD     Stack: 3,5
Opcode: STOP    Stack: 8
Returned:
gasUsed : 9
```

How do I use ethereumjs in nodejs?

**Comment by holgerd77** [comment]
Sorry, I guess the experience within the whole team with `.mjs` files and the added ES6 support in Node.js is very limited, think everyone is running with `ts-node` since this feels more natural along TypeScript development.

This code works in a plain JS file though:

```javascript
const Common = require('@ethereumjs/common').default
const common = new Common({ chain: 'mainnet' })
```

Not sure if this brings you further of if you need/want the direct `.mjs` support.

This should be a relatively common error/problem with default exports being used in Node.js I guess? 🤔  We are not doing anything fancy here I would say, just `export default class Common`.

For the examples we have decided to just stick to one syntax, this would otherwise blow the READMEs too much.

Will close here for now, feel free to reopen if you feel this is not sufficiently handled yet.

**Comment by TimDaub** [comment]
Hey @holgerd77,

ESM support has landed in ts-node: https://github.com/TypeStrong/ts-node/issues/1007
I'm encouraging you to take a look. ESM in nodejs already makes a lot of sense and it will make sense in ts-node too I believe.

**Comment by holgerd77** [comment]
@TimDaub hi there, thanks for letting us know. Sorry, we don't have the capacity right now to deal with this issue, so this will likely take some more time (weeks I guess).
