### ISSUE TITLE
VM: Test setup didn't catch Node 10 bug

### ISSUE THREAD

**Issue by holgerd77** [ethereumjs/ethereumjs-monorepo#1155]
Node 10 support was broken in the VM v5 releases up to version `v5.1.0` due to the usage of `globalThis` for browser detection, bug was reported by @fvictorio from Hardhat. This is now fixed along the `v5.2.0` release via this commit 987f5d5566658cd4484d6f07415dd375b22ac5b7. We have "Node versions" tests setup in CI which were running also [with Node 10](https://github.com/ethereumjs/ethereumjs-monorepo/runs/2135834815?check_suite_focus=true) at the moment of reporting (and test were passing).

So there is the question why this has not been triggered a test failure. This should be examined at some point, eventually the CI setup is wrong respectively not matching the production environment setup sufficiently.

Some analysis from @alcuadrado quoting from chat:

>the test doesn't catch it because it uses ts-node/register
>which transpiles globalThis
>but the published build doesn't
>so it node10 throws because globalThis is undefined, and that statement does .window on it

Second post on this, somewhat later:

>I think there's an issue in how the tests are run
>they seem to use a different typecript config than the production builds
>otherwise this should have been caught by the ci
>it may be the case that the CWD isn't set correctly to each package's dir before running its tests
>so its tsconfig.json isn't loaded by ts-node

**Comment by holgerd77** [comment]
Update: I guess this is still relevant and should be picked up at some point.

**Comment by holgerd77** [comment]
Update: This is still relevant and should be picked up.

**Comment by ryanio** [comment]
I will look into this.

**Comment by ryanio** [comment]
I found a TypeScript [globalThis shim](https://github.com/microsoft/TypeScript/blob/27616dd523279a5d699d2154edb4de6abc8234ad/src/services/globalThisShim.ts) that must be the reason why running tape with `ts-node/register` polyfills `globalThis`.

I am on Node 10 and when I do `console.log(globalThis)` I get the global this object rather than an error, and `console.log(process.version)` returns `v10.16.2`.

I did another test locally, `globalThis.queueMicrotask` was added in Node v11 so on `nvm use 10` I get `console.log(globalThis.queueMicrotask)` => `undefined` and on `nvm use 16` I get `[Function: queueMicrotask]` within the lib `src` via `tape`, so I think the right node version is being run. I could also test this on ci but I assume it's the same.

**Comment by holgerd77** [comment]
TBH, I can't completely interpret the analysis. Can we do something in CI to prevent such a non-detection in the future? 🤔

**Comment by ryanio** [comment]
Possibly we could write some vanilla JS tests to be run against the published build. If we run the tests in TypeScript then I think it will always shim `globalThis`, but that may be one of the only things polyfilled for backwards compatibility, other bugs should get caught in the current test setup (like if we used a new node feature in an old node version, that would throw)

**Comment by holgerd77** [comment]
Ok, then I would cautiously close here if we regard this as something rather in the "not worth the effort" category. Let me know if I falsely interpreted this, also to everone else: feel free to reopen if you think otherwise.
