### ISSUE TITLE
Incompatible Library versions (TypeScript errors) / Peer dependency switch

### ISSUE THREAD

**Issue by alcuadrado** [ethereumjs/ethereumjs-monorepo#1200]
I'm getting compilation errors when i upgrade some of the libraries.

For example, if I have `@ethereumjs/vm`, `@ethereumjs/block`, and `@ethereumjs/blockchain`, and upgrade the first two, yarn may decided not to upgrade `block` inside of `@ethereumjs/blockchain`. 

This leads to my project having multiple, sometimes incompatible, versions of the same libs. Even if the changes were backwards compatible, typescript may decided that two types are incompatible.

This image shows an example of this:

![image](https://user-images.githubusercontent.com/176499/114450727-c105e000-9bac-11eb-8912-3c8c6faf4fd5.png)

This error comes from incorrectly declaring some things as `dependencies` when they should be `peerDependencies`. Failing to do this properly leads to a very fragile system that breaks in this unexpected way, and can be easily bloated with multiple versions of the same library. 

I think I mentioned this problem before, and also pointed to [this excellent article](https://lexi-lambda.github.io/blog/2016/08/24/understanding-the-npm-dependency-model/) explaining what peer dependencies are and when should be used.

As an incomplete workaround, you can delete all of your project's `node_modules` and `yarn.lock`/`package-lock.json`. This would only help you compile your project, but it may be just transferring the problem to your users.

**Comment by ryanio** [comment]
Thanks for detailing the issue.

I can work on a PR for this and include #1182.

My current understanding is that any dependency that is returned as part of the package's exported interface should be moved to a PeerDependency. Let me know if that sounds right. 

Are there any tests we can add to proactively keep an eye out for this issue? especially if a new dep is added to an interface and wasn't moved to a PeerDep, seems like something that may be overlooked in the future. It would be great if we can create something to add to the new file at `packages/vm/tests/api/types.spec.ts`

**Comment by alcuadrado** [comment]
> My current understanding is that any dependency that is returned as part of the package's exported interface should be moved to a PeerDependency. Let me know if that sounds right.

Right. This includes things like BN, tx, block, and blockchain, but there's probably more.

> Are there any tests we can add to proactively keep an eye out for this issue?

I think this can help: https://api-extractor.com/

**Comment by ryanio** [comment]
> Right. This includes things like BN, tx, block, and blockchain, but there's probably more.

For `BN`, we currently import and use it from `ethereumjs-util`. Should `ethereumjs-util` become a peer dependency then if the exported interface contains a `BN`? Or should we list `BN` as a separate peer dep with the version range from `ethereumjs-util`?

**Comment by holgerd77** [comment]
Ok, I guess the only (?) way to properly solve this is to switch to peer dependency declarations all over the place (respectively: everywhere where it is structurally needed) in the next round of breaking releases? 🤔

Have added this to the v6 release planning issue for now (@alcuadrado: this stand roughly for: breaking releases on (more-or-less) all monorepo libraries, we plan to do this some time after the successful London HF since we have got quite some list already and would like to execute on this).

I would also suggest that we start to systematically collect dependencies in this issue (have reframed on the title) which we want to convert to `peerDependency` relationships:

### Peer Dependency Relationships

- `VM` <- `Tx`
- `VM` <- `Block`
- ...

Feel free to directly add on this list by updating the comment (let me know if you do not have got the respective rights here, I always assume this is possible).

**Comment by ryanio** [comment]
I took a preliminary look through our exported APIs for each package and updated the list above, would appreciate another set of eyes on anything missing or unneeded. cc @alcuadrado

**Comment by holgerd77** [comment]
@ryanio thanks, that's already a nice list! 😄

**Comment by alcuadrado** [comment]
> For `BN`, we currently import and use it from `ethereumjs-util`. Should `ethereumjs-util` become a peer dependency then if the exported interface contains a `BN`? Or should we list `BN` as a separate peer dep with the version range from `ethereumjs-util`?

Sorry for this late answer. I think in that case, BN should be a peer dependency of ethereumjs-util (it's part of it's public API), and also of the VM/Block/Tx (same reason)

**Comment by acolytec3** [comment]
Do we still need this now that we're on NPM v7? Feels like this has been addressed as much as we're going to do?

**Comment by holgerd77** [comment]
@acolytec3 hmm, while we've gotten more sceptical on this lately I guess this is still in the open, so I wouldn't close for now. Ryan did some test implementation in #1402, we aborted this for now but didn't necessarily conclude that the issue has been solved.

And, as some side comment: I guess the switch to v7 for our development setup has not changed anything which would contribute to solve this issue, let me know if I am mistaken here.

I've gotten generally more sceptical on this issue myself, since no one has further picked this up or has been complaining on this since the issue got opened in April this year. Maybe let's nevertheless keep this open a bit longer until we have some more solid reasoning here and some final decision what to do (or not to do).

**Comment by alcuadrado** [comment]
> Maybe let's nevertheless keep this open a bit longer until we have some more solid reasoning here and some final decision what to do (or not to do).

We've experienced different problems because of this quite often. I think it's right after one of the libraries releases a new version. We just didn't report it again because this issue existed.

**Comment by holgerd77** [comment]
Will finally close here, feel free to reopen at some point if there is need or demand. This would then need some re-analysis anyhow.
