### ISSUE TITLE
VM, Block, Tx, Other: Replace Tx Type Checks with Functionality Checks

### ISSUE THREAD

**Issue by holgerd77** [ethereumjs/ethereumjs-monorepo#1242]
With the introduction of typed txs we have now tx typed checks in various parts of the monorepo, see e.g. [VM.runTx()](https://github.com/ethereumjs/ethereumjs-monorepo/blob/master/packages/vm/lib/runTx.ts#L140).

In most cases (all?) these checks are not about one specific tx type but about if a tx supports some dedicated functionality (Access Lists, 1559 fee market). The problem with the tx checks is that these are error prone when future tx types are added and these checks are not updated.

First suggestion here would be to replace the type checks with functionality flags added to the tx classes, so e.g. `tx.supportsEIP1559` or `tx.supportsAccessLists`. Open for further discussion and/or suggestions though.

**Comment by ryanio** [comment]
Good suggestion, although I would be hesitant to introduce a new method per feature as that might get unwieldy. Perhaps we can introduce a `tx.supports(feature: TxFeature)` method with `TxFeature` being an enum of tx functionality (`AccessList`, `FeeMarket`) that can be added to over time.

> The problem with the tx checks is that these are error prone when future tx types are added and these checks are not updated.

I agree this is an issue in probably several parts of the code base and type definitions. It would be nice to add some more security to this where unhandled tx types throw so that they aren't missed. I can also imagine it would be useful to maintain a list of places that need to be updated with the addition of new tx types, so we have a checklist every time that can be followed.

**Comment by holgerd77** [comment]
@ryanio yeah, all good suggestions, thanks! 😄
