### ISSUE TITLE
Block: EIP-1559 BaseFee Default Value

### ISSUE THREAD

**Issue by holgerd77** [ethereumjs/ethereumjs-monorepo#1250]
This was mentioned by @ryanio on the EIP-1559 PR #1148 review (just can't find the comment reference itself any more 😄 ): currently the `BaseFee` for an EIP-1559 block is set to `new BN(1)` as a [default value](https://github.com/ethereumjs/ethereumjs-monorepo/pull/1148/files#diff-f1ede6d7e271344dfe9b65d51852281d30f70cf3e415e8a15f1c3ab3048240a0R223).

I introduced this along some update rework. I also have to say that I chose some relatively arbitrary value here, since I couldn't find a good argumentation for some specific value.

Therefore it might make sense to have this discussion here a bit more explicit so that it doesn't get lost within the review comments.

So what would one want to have as a default here?

Potential candidates are:

- The initial base fee from the EIP: 1000000000
- 0
- 1
- Other?

So what would be a practical choice here for some default block initialization, maybe also from a developer scenario (but not necessarily limited to that) perspective?

I guess my vague inner argumentation for 1 was to have *some* value here so that not all price checks are just getting deactivated, but also not having something very high so that one can operate with low fees set in development environments.

Not sure if this holds and if 1 is a good value though.

Would also be interested in the opinion from @alcuadrado here.

**Comment by jochem-brouwer** [comment]
I think it makes sense to use the initial base fee. We should not set it to 0 or 1 since in practice this is impossible, the absolute floor of the base fee is 7 wei.

**Comment by holgerd77** [comment]
What is the concrete argument to set it to the initial base fee? At the end this is just some one-time start value? Would want to keep this a bit longer in discussion, also don't have the concrete answer yet.

What would be with setting this to 7 wei (is this limit generally actually checked somewhere?)? Would this also be a candidate?

**Comment by ryanio** [comment]
I read in the R&D discord that the spec wrongly alludes that the base fee can go to zero and implicitly the minimum is 7 wei.

I'm not sure if it matters what our default is since it's highly dependent on the parent block context, but it should probably be above 7 so it's at least not an invalid or unreachable value.

In a blockchain context where you have the parent block jochem already added a handy `parentBlock.calcNextBaseFee()`, so that is probably what I'll use as the default when updating the BlockBuilder for 1559 blocks 👍

**Comment by holgerd77** [comment]
Just to complete the picture here, I think one thing where this might be relevant is for `tx.getUpfrontCost(baseFee?)`, and this method is mainly (only?) used in `VM.runTx()` within the following code:

```typescript
// Validate gas limit against base fee
  const basefee = tx.getBaseFee()
  const gasLimit = tx.gasLimit.clone()
  if (gasLimit.lt(basefee)) {
    throw new Error('base fee exceeds gas limit')
  }
  gasLimit.isub(basefee)

  // Check from account's balance and nonce
  let fromAccount = await state.getAccount(caller)
  const { nonce, balance } = fromAccount

  if (!opts.skipBalance) {
    const cost = tx.getUpfrontCost(block.header.baseFeePerGas)
    if (balance.lt(cost)) {
      throw new Error(
        `sender doesn't have enough funds to send tx. The upfront cost is: ${cost} and the sender's account only has: ${balance}`
      )
    }
  }
```

So this is where we might have UX implications, e.g. if someone in a dev context doesn't want to use the `skipBalance` option. Just making potential scenarios up for thought inspiration. 😄

**Comment by holgerd77** [comment]
So we keep `BaseFee` default value at `7` then (see code [here](https://github.com/ethereumjs/ethereumjs-monorepo/blob/master/packages/block/src/header.ts#L220))?

**Comment by holgerd77** [comment]
This was decided and published to be set at `7`, will close.

**Comment by mfornet** [comment]
If a [default value is used](https://github.com/ethereumjs/ethereumjs-monorepo/blob/master/packages/block/src/header.ts#L218-L222) vs the correct value from the block, we can't reliably serialize and compute the hash of a block, since it [depends on it](https://eips.ethereum.org/EIPS/eip-1559#block-hash-changing). While experimenting with this I've seen blocks in Ropsten that are using `baseFeePerGas` of 8 instead of 7, so I wasn't able to compute the proper hash of such blocks in this scenario.

I understand that finding reasonable defaults are a good compromise vs throwing, but in this case if the default is not correct, the hash value of the block won't match the correct hash, which can be really problematic.

**Comment by holgerd77** [comment]
There are various use cases where people just want to operate in some block context and it is not necessary to set all the values. We therefore set somewhat reasonable default values for all the block values (I guess I am repeating the argumentation from @ryanio here a bit). The argument with the hash changing would actually go for all these values (block number, gas limit, nonce, whatever you take).

Not sure we can think about to at least provide the possibility to enforce a full instantiation e.g. with an option like `useDefaults` or something which defaults to `true` and one could set to `false` to allow for an intantiation only if all the values are provided? Would this eventually make some sense?

**Comment by holgerd77** [comment]
(this would need some additional thought though if this is really worth it since a new option always somewhat add additional complexity to a library)
