### ISSUE TITLE
VM: getOpcodesForHF() should perhaps also return off/on stack

### ISSUE THREAD

**Issue by yann300** [ethereumjs/ethereumjs-monorepo#1270]
It is often useful to get the amount of slot that a specific opcode consumes and add in the stack.
This was I think the case before (might be quite a long time ago though).

**Comment by yann300** [comment]
I am referring to https://github.com/ethereumjs/ethereumjs-monorepo/blob/a03be0fd11ea7e78b5689bb723aff70a97c9e3b1/packages/vm/lib/evm/opcodes/codes.ts#L4

**Comment by holgerd77** [comment]
The function we have officially exposed through the API is `VM.getActiveOpcodes()`, is this where you would want to have this added?

A usage example is:

```typescript
import VM from './lib'
const vm = new VM()
vm.getActiveOpcodes()
```

Result looks a bit like:

```javascript
{
  245 => Opcode {
    code: 245,
    name: 'CREATE2',
    fullName: 'CREATE2',
    fee: 32000,
    isAsync: true
  },
  250 => Opcode {
    code: 250,
    name: 'STATICCALL',
    fullName: 'STATICCALL',
    fee: 700,
    isAsync: true
  },
}
```

Hmm, I had a look into some very old version of the library (2 years ago) and this has been out already: https://github.com/ethereumjs/ethereumjs-monorepo/blob/dynamic-execution/lib/evm/opcodes.ts

I wonder if we want to re-add since we have no internal use for that after a refactoring of how the stack works. So this would be just some information as some convenience exposure for library users with no real usage in the VM itself. These kind of things always have some tendency to get forgotten on the way and get inaccurate over time.

**Comment by holgerd77** [comment]
Any other opinions here?

**Comment by ryanio** [comment]
I think @yann300 would be referring to adding properties to the `Opcode` list that would indicate how many pops and pushes each does to the stack. I took a look at geth's opcode [jump_table](https://github.com/ethereum/go-ethereum/blob/master/core/vm/jump_table.go#L144) and they have properties `minStack` and `maxStack`.

It doesn't seem like we've had a need for this yet though, @yann300 could you explain more how it would be useful for you?

**Comment by holgerd77** [comment]
Seems we will rather not implement, will close for now. @yann300 feel free to reopen if you see a stronger need for this and would like to make another pledge here.
