### ISSUE TITLE
Key in storage proof not matching storage slot key

### ISSUE THREAD

**Issue by gpsanant** [ethereumjs/ethereumjs-monorepo#1279]
This is a storage proof I received via web3:

```
[
  {
    key: '0xa665a45920422f9d417e4867efdc4fb8a04a1f3fff1fa07e998e86f7f7a27ae3',
    value: '0x7b',
    proof: [
      '0xe3a120e00ec213300e9930eb0c94155c094e65dec548f399db696a0be9e50ae615c0a77b'
    ]
  }
]
```

When I input this into the tree package, I get a tree one node:

```
[
  <Buffer 20 e0 0e c2 13 30 0e 99 30 eb 0c 94 15 5c 09 4e 65 de c5 48 f3 99 db 69 6a 0b e9 e5 0a e6 15 c0 a7>,
  <Buffer 7b>
]
```

The value is correct here but why does the key not match the storage key above?

Any help is appreciated, thanks :)

**Comment by ryanio** [comment]
hey @gpsanant, what do you mean `When I input this into the tree package`? could you share some code or more details about reproduction?

**Comment by gabrocheleau** [comment]
Hey @gpsanant . As @ryanio mentioned it's hard to figure this out without a reproduction procedure. However I notice that bytes from index `2` of the web3 `proof`  `'0xe3a1**20e00ec213300e9930eb0c94155c094e65dec548f399db696a0be9e50ae615c0a77b**'` have the same value as the `key/value` pair from the tree package. 

Maybe the issue comes from the key being encoded in web3 both not encoded in the tree package? The tree package has `Trie` and `SecureTrie` classes, and if I recall correctly, if you want to get the same (encrypted) values as on the Ethereum blockchain, the `SecureTrie` is what you should use.

Although not directly related, this tutorial has some info on that: https://github.com/gabrocheleau/merkle-patricia-trees-examples#example-1a---creating-and-updating-a-base-trie

**Comment by holgerd77** [comment]
Will follow the suggestion from @gabrocheleau and close here, feel free to reopen if still an issue.
