### ISSUE TITLE
Util: Wasm modules for crypto

### ISSUE THREAD

**Issue by s1na** [ethereumjs/ethereumjs-monorepo#1304]
This is a spin-off discussion from ethereumjs/ethereumjs-util#195 which aims to assess whether it makes sense to use Wasm modules for crypto.

The arguments for this approach being that WebAssembly is now available everywhere (node & browsers) in comparison to `node-gyp` bindings (used by the `keccak` and `secp256k1`) which is (as the name suggests) only available in `node` (in browser a native JS code is executed).

What remains to be seen is how the performance of an efficient Wasm module compares against the `node-gyp` bindings and native JS code.

**Comment by holgerd77** [comment]
Hi @paulmillr, circling you in here (into a very old issue), what is your idea on WASM for the crypto stuff?

**Comment by paulmillr** [comment]
@holgerd77 seems like a bad idea. How do you verify the stuff you're downloading is good, and not malware? NPM doesn't have signed code. 

1. The compiled code could be replaced with malware completely.
2. Developed machines could get infected and produce "malware" with useful code, they won't even know it's happening. This happened recently in Swift ecosystem
3. All cryptographic primitives are fast enough to be used without wasm in web3 apps. By fast I mean "lots of operations to fit in one 120fps frame" (8.3ms).  The only exception to this is bls12-381. Pairing takes 20 milliseconds in js. With low-level libs it could be 20-50x faster.
4. Wasm takes a lot of space, it's binary.
5. Security-wise it still won't matter because of gc and jit in js code.

If NPM gets signed code in place and you'll be able to verify it, and there would be infra for reproducible builds, then it would be better.

**Comment by paulmillr** [comment]
For the record: noble-hashes achieves 1.1 million sha256() operations per second with pure js. That's without loop unrolls! We can do faster, if needed.

**Comment by holgerd77** [comment]
@paulmillr great, this is a lot of useful insight to put this in some perspective. 🙂  Thanks a lot for this detailed write-up. 🙏

Will close here for now.
