### ISSUE TITLE
intanceof keyword not working properly for FeeMarketEIP1559Transaction

### ISSUE THREAD

**Issue by yann300** [ethereumjs/ethereumjs-monorepo#1313]
This happens in the browser:

![instanceof](https://user-images.githubusercontent.com/6940742/122763916-2ce88100-d29f-11eb-90ad-73cc66e010b2.png)

The tx is seen as being an ` FeeMarketEIP1559Transaction` but `tx instanceof FeeMarketEIP1559Transaction` returns false.
Might be a browser specific issue. I am still checking whetther that can be an issue in our side.

**Comment by yann300** [comment]
Would be great if you guys can confirm that this is working ok currently with a regular build.

**Comment by ryanio** [comment]
hey @yann300 yes let me help look into this for you. how are you bundling for the browser, webpack or browserify or some similar tool?

In our ci we use `karma-typescript` that runs `runTx.spec.ts` which has 1559 txs and I just tested and it's entering that block correctly.

If you have a custom wrapper over that tx class I could see the `instanceof` check not working. I know it's a bit brittle, but the reason we use it is because TypeScript automatically casts it so we can write more concise code. If it's too inflexible we could consider changing it to checking e.g. `tx.type === 2` then doing `tx = tx as FeeMarketEIP1559Transaction` so we can get access to e.g. `maxFeePerGas` within the code block.

**Comment by yann300** [comment]
Thanks for the help ;)
yes we are using webpack.
It seems that running `npm dedupe` fixes the issue (https://docs.npmjs.com/cli/v7/commands/npm-dedupe).
We are testing this solution, will let you know our findings.

**Comment by holgerd77** [comment]
@ryanio I guess that's another case for our `tx.supports(featureX)` function discussed in #1242 (we shouldn't go back to these type checks if possible). Seems we should give this some priority (will add an `urgent` label on the issues), if @yann300 and the Remix team are running into this so early and in such a generic context this will likely also cause problems for others.

**Comment by yann300** [comment]
For the moment we were able to mitigate the issue by running `npm dedupe` and this is working...

**Comment by holgerd77** [comment]
Solved by #1315 (not yet released), will close.
