### ISSUE TITLE
Release new version of @ethereumjs/client

### ISSUE THREAD

**Issue by ryanio** [ethereumjs/ethereumjs-monorepo#1365]
The last [`ethereumjs-client`](https://www.npmjs.com/package/ethereumjs-client) release was over a year ago, and since bringing it into the monorepo there has been extensive changes and improvements to the early development of the project.

This is a tracking issue to deprecate the old `ethereumjs-client` on npm and release the new one under the `@ethereumjs` namespace.

**Comment by holgerd77** [comment]
Some additional context and thoughts here: I guess we are still *pretty* far away from a v1.0 release (one year plus) since there is various substantial functionality missing (tx pool, block production, tip of the chain behavior, reorgs, ...) which we just can't catch up within a few weeks or so. A real production client comes with certain expectations and even if we get the things from above working on a basic level, we are still somewhat far away from the functionality clients like Geth or Erigon are providing, their tx pool alone is highly sophisticated stuff and took weeks (months?) to implement. And we haven't even synced once to the tip of the chain of mainnet or a major test network. 😜

So I would really suggest to somewhat stay modest here. 🙂 I guess if we start with a v0.1 release and drop the pre-release state that would be already courageous. 😋

One thing also to consider strongly when planning on this: the Merge is "somewhat" around the corner and I guess it will lead to too much wasted ressources if we put too much energy into completing here on all fronts on a classic Eth 1.0 client when larger parts of this are thrown away along the respective integration. So we should in doubt rather focus on bringing things to work under merge conditions and then see after the merge how we position the client within this changed environment setting.

All this doesn't mean though that we can't pick up with regular client releases though and make our client a more public product. 😄

**Comment by holgerd77** [comment]
My suggestion here:

We finish the following:

- Basic Tx Pool #1176 (@holgerd77, can be taken over if wished)
- Tip of the chain behavior #1132 (@jochem-brouwer and/or @acolytec3)
- Block assembly (@acolytec3)
- Block producing (clique protocol), (OPEN)

Then we bring the README up to date and also add a very explicit list what the client is and is not capable to do and then we release as `v0.1` (following the last [v0.0.6](https://github.com/ethereumjs/ethereumjs-client/releases/tag/v0.0.6)) release within the old `ethereumjs-client` namespace) and drop the `pre-release` to indicate that this is a new release quality respectively the client has taken a substantial leap on development and feature completeness.
