### ISSUE TITLE
Create client docker images for multiple platforms

### ISSUE THREAD

**Issue by acolytec3** [ethereumjs/ethereumjs-monorepo#1371]
Now that the client is getting ready for a v1.0 release, we should create standalone docker images that allow the client to be run on multiple architectures (x86/ARM/mac) without requiring users to build from source.  Thoughts on this?

**Comment by holgerd77** [comment]
I would very much say that this is too early in the process, as argued [here](https://github.com/ethereumjs/ethereumjs-monorepo/issues/1365#issuecomment-891784518) we are still pretty far away from a v1 client release.

I would suggest not to put too much effort into things like this and rather close here (we haven't even picked up on a substantial user base from the core JS community, simply because we haven't integrated the client into our release cycles yet).

**Comment by holgerd77** [comment]
Will close here for now.
