### ISSUE TITLE
Util: Deprecate ethereumjs-units and integrate into Util

### ISSUE THREAD

**Issue by holgerd77** [ethereumjs/ethereumjs-monorepo#1397]
As discussed with @ryanio the [ethereumjs-units](https://github.com/ethereumjs/ethereumjs-units/) package should be deprecated (somewhat separate from this issue) and the functionality integrated into the `Util` package.

This would be useful especially for denominations when using the tx library.

Currently that look like this which is not very user friendly and somewhat error prone:

```typescript
const txData = {
  from,
  nonce: 0,
  gasPrice: 1000000000,
  gasLimit: 21000,
  to,
  value: 1,
}

const tx = Transaction.fromTxData(txData, { common })
```

In `Util` this should likely be a separate module `units`. Otherwise we should give the API some additional thought before we integrate (I wonder e.g. if we have some use case for this `lazyConvert` method/API?).

**Comment by ryanio** [comment]
I can work on this, it would be nice to have a simple internal units util.

`bn.js` doesn't have decimal support though, so we'll have to do something about that, it looks like `ethereumjs-units` uses `bignumber.js`.

For our own monorepo use, I think it might be more helpful to return a `BN` based in wei, something like this:

```typescript
const txData = {
  value: Units.ether(1),
  maxFeePerGas: Units.gwei(10),
  maxPriorityFeePerGas: Units.gwei(10)
  ...
}
```

although this could be the same:

`Units.convert(value: number | string | BN, from: Unit, to: Unit): string`

where you could do

`Units.convert(10, Unit.Gwei, Unit.Wei)` => `10000000000`

But we do need to return strings unfortunately for decimal support:

`Units.convert(1, Unit.Wei, Unit.Ether)` => `0.000000000000000001`

I also don't really see the need for `lazyConvert`, since we are mostly developer tools I'm not sure when we need to input or output formatted strings like that.

**Comment by holgerd77** [comment]
I actually think we should still execute on this (3y old) issue but simply add a super-simple `units.ts` file to `@ethereumjs/util` and more or less only from-scratch "implement" (add) the API Ryan suggested:

```ts
const txData = {
  value: Units.ether(1),
  maxFeePerGas: Units.gwei(10),
  maxPriorityFeePerGas: Units.gwei(10)
  ...
}
```

So, these *three* methods (returning a BigInt), exactly named like this, add a few tests and *NOT* having a look at all any more at this endless discussion from the tries of the closed PR and **ALSO FULLY IGNORE THE ethereumjs-units package**.

So this would give this the 2-3 hour task it deserves and it would be pretty useful to fill txs or blocks where we atm do something like:

```ts
createLegacyTx({
  gasPrice: 41000000000
  // ...
}, { common })
```

(as an additional 2-3 hour task completion it would then actually be nice to apply this new API throughout the monorepo for test block/tx creation where useful)

And then we'll close here.

@scorbajio can I assign you here? (feel free to un-assign if not fitting)

**Comment by holgerd77** [comment]
(so, again, the most important part here is to *not* overthink 😂 , so really only a static class `Units` (I think we don't need tree shaking here, this is so few code and more handy to have this as one object to access) and then two methods:

- `Units.ether(1)`
- `Units.gwei(10)`

And then returning the fully expanded amount in `wei` as BigInt (likely it makes sense for the methods to support both numbers and BigInt as input).

NO MORE UNITS!!! (these discussions were killing us in the first rounds 😂)
NO WAY BACK!!! (not necessary for now)

(I am pretty sensitive on this since during the first iteration this was a full 6-8 week discussion/iteration round and lead to no integrated result at the end)

)
