### ISSUE TITLE
Difference between gasUsed and execResult.gasUsed

### ISSUE THREAD

**Issue by yann300** [ethereumjs/ethereumjs-monorepo#1446]
the `afterTx` event (link below) used to contain 2 different values for the gas consumption (tx cost and exec cost): `{ gasUsed }` and `{ execResult: { gasUsed } }` . The latter seems now to also return the tx cost.

https://github.com/ethereumjs/ethereumjs-monorepo/blob/587ee70ae9b21cfe9c0eb438d946248382468c31/packages/vm/src/runTx.ts#L473

**Comment by ryanio** [comment]
Oops, I remember this TODO actually, I should have more carefully looked into it rather than hastily changing: https://github.com/ethereumjs/ethereumjs-monorepo/pull/1375/files#diff-b48b85860e898fbfe1fec61ec4e174d679faf07ec106c31a847c8dad7f7d5adeL386-L387

Sorry about that. I need to dig in to understand this better. I can also do a patch release to fix, and I can add a test too to ensure it doesn't happen again. I guess none of our existing tests checks this value?

I also noticed that the debug output is outputting the same variable instead of execResult.gasUsed: https://github.com/ethereumjs/ethereumjs-monorepo/blob/587ee70ae9b21cfe9c0eb438d946248382468c31/packages/vm/src/runTx.ts#L361-L362

**Comment by holgerd77** [comment]
Just for the record: the mentioned PR #1375 has been merged on July 25, so there are the two VM releases `v5.5.1` and `v5.5.2` affected by this.

**Comment by holgerd77** [comment]
Update: oh, just stricing the above comment through again, I was writing based on the un-edited text I received via mail.

@ryanio so, just for the (updated) record 😄: you came to the conclusion after further analysis that #1375 didn't introduce this as a new bug?

**Comment by ryanio** [comment]
> @ryanio so, just for the (updated) record 😄: you came to the conclusion after further analysis that #1375 didn't introduce this as a new bug?

I thought it might have, but the line I was considering ([here](https://github.com/ethereumjs/ethereumjs-monorepo/pull/1375/files#diff-b48b85860e898fbfe1fec61ec4e174d679faf07ec106c31a847c8dad7f7d5adeL386-L387)) was actually `gasRefund` not `gasUsed`.

It could still be introduced by that PR, but it's not immediately obvious to me yet.

One common cause is that It could be a mutated BN we need to clone that's getting accidentally modified.

**Comment by holgerd77** [comment]
Additional note: this should be easily be verifiable by looking at some execution with `VM.runTx()` I guess, e.g. by looking at the results of one of the tests in [runTx.spec.ts](https://github.com/ethereumjs/ethereumjs-monorepo/blob/master/packages/vm/tests/api/runTx.spec.ts).

**Comment by ryanio** [comment]
@yann300 any further thoughts or follow-up here? do you remember what you ended up doing?

"gasUsed" is a little confusing because we have two different meanings:
 - cumulativeGasUsed (as used in the tx receipt, gas used in the block including the tx)
 - txGasUsed (gas used *only* for one tx)

I would like to at least resolve my comment above about the second log output not outputting `results.execResult.gasUsed`, nd meanwhile would be good to note the differences between the two values in the typedoc (if there is)

**Comment by holgerd77** [comment]
@ryanio maybe we want to rename on the breaking releases? If so, could you directly add a note with suggested names to #1024 ?

**Comment by ryanio** [comment]
that's a good idea, will do, let me dig into it a bit more and I'll report my findings here and add next steps to that issue

**Comment by holgerd77** [comment]
> that's a good idea, will do, let me dig into it a bit more and I'll report my findings here and add next steps to that issue

👍  🙂 

Ok, have already added the link to the comment here as a placeholder so that we don't forget.

**Comment by ryanio** [comment]
Ok I've investigated further, and based on `evm.ts:L457` below they do seem to be the same value:

https://github.com/ethereumjs/ethereumjs-monorepo/blob/aa7d323a1bddc5e1250c6861402c733037f32fa2/packages/vm/src/evm/evm.ts#L456-L460

Which I think is fine, it was probably a decision to surface that important number in `EVMResult` from `ExecResult`:

https://github.com/ethereumjs/ethereumjs-monorepo/blob/aa7d323a1bddc5e1250c6861402c733037f32fa2/packages/vm/src/evm/evm.ts#L26-L33

https://github.com/ethereumjs/ethereumjs-monorepo/blob/aa7d323a1bddc5e1250c6861402c733037f32fa2/packages/vm/src/evm/evm.ts#L44-L60

I will open a PR improving the debug logs a bit and fix some typos I noticed.

If you agree this is fine and no further action is needed then we can remove this issue from the breaking changes issue.

I did also come across these lines though, not sure what the backstory is here, @jochem-brouwer any thoughts?

https://github.com/ethereumjs/ethereumjs-monorepo/blob/aa7d323a1bddc5e1250c6861402c733037f32fa2/packages/vm/src/evm/evm.ts#L197-L198

**Comment by holgerd77** [comment]
@jochem-brouwer can you please write a qualified comment on the state of this and eventually close here? 😋

**Comment by jochem-brouwer** [comment]
@holgerd77 Yup!

This can be closed, as in V6 we have now renamed the vars:

`execResult.gasUsed` is now `execResult.executionGasUsed`

`gasUsed` is now `totalGasSpent`

The difference in the name now explains what the semantical difference is. In `runTx`, the `totalGasSpent` includes the `executionGasUsed` (thus `execResult.gasUsed`) and the upfront cost (to pay for the tx cost (21000 for normal txs, some more for txs which create a contract)) and the data cost (this includes the access list cost). The `executionGasUsed` is "simply" the `gas` used by the execution engine, i.e. the cost to actually execute the code. 

Will close.

**Comment by holgerd77** [comment]
Thanks a lot, that's a really great explanation! 🙏🙂👍
