### ISSUE TITLE
Monorepo / Client: Rinkeby CLI test are often failing

### ISSUE THREAD

**Issue by holgerd77** [ethereumjs/ethereumjs-monorepo#1462]
The client CLI tests (see [client-build.yml](https://github.com/ethereumjs/ethereumjs-monorepo/blob/master/.github/workflows/client-build.yml#L48)) are often failing lately, especially the run against the Rinkeby network, see e.g. [this](https://github.com/ethereumjs/ethereumjs-monorepo/blob/master/.github/workflows/client-build.yml#L48) test run.

This should be examined and fixed.

**Comment by ryanio** [comment]
I have noticed this over the past week as well, the network might be overloaded and having difficulty connecting to a peer with available slots since the error is a timeout for the test and nothing else, but I will investigate further in case it is any changes on our side.

**Comment by ryanio** [comment]
Yeah I just tried with
`npm run client:start -- --network=rinkeby`
vs `--network=goerli`
and rinkeby is extremely busy right now.
This is why I did not make it a required check, since we are at the mercy of the p2p pool at any point in time.
I originally wanted ropsten/rinkeby to have one chain each PoW/PoA but ropsten is always overloaded like this 😄

We can think of changing rinkeby to another less popular testnet chain (not sure what would be a next candidate), or only keep goerli since that has definitely been the most reliable.

**Comment by holgerd77** [comment]
Ok, then let's only keep Goerli for now, these always failing CI runs have otherwise too substantial other side effects (e.g. subtantially increasing the risk to overlook other failures like the non-mandatory Hardhat tests, since one gets too used to just seeing a red x for the test runs).

Will do add along #1463 and then admin merge, guess this should be ok in this context since only touching CI.

**Comment by holgerd77** [comment]
Closed by #1463.
