### ISSUE TITLE
Common: add BSC chain config

### ISSUE THREAD

**Issue by atrinitytv** [ethereumjs/ethereumjs-monorepo#1535]
Would be really nice to get native BSC support :)

**Comment by atrinitytv** [comment]
Would this help for getting a common made for BSC?

{ChainID: 56 Homestead: 0 DAO: DAOSupport: false EIP150: 0 EIP155: 0 EIP158: 0 Byzantium: 0 Constantinople: 0 Petersburg: 0 Istanbul: 0, Muir Glacier: 0, Ramanujan: 0, Niels: 0, MirrorSync: 5184000, Bruno: 13082000, Berlin: , YOLO v3: , Engine: parlia}

**Comment by holgerd77** [comment]
Hi there,
thanks for the suggestion.

We've discussed this in the team again. Sorry, but if the BSC chain is coming with its own hardforks (we didn't know about that before), this is rather too deep reaching into our code bases and we wouldn't do an integration on such a level for a third-party chain.

So we would rather encourage you (or anyone else interested) to do a wrapper or a fork on the library and add a respective chain files together with dedicated hardfork and EIP definitions you need for your chain. We have a lot of generic structures in place (checking for EIP activations, comparing HFs,...) which should significantly help you on such an implementation.

Will close here.

**Comment by mjpowersjr** [comment]
Sorry to revive a old thread - does anyone know if a BSC fork being developed / maintained? 

I'm not finding anything via Google, etc. - I figured it was worth a shot to ask here before digging deeper into the codebase.

**Comment by acolytec3** [comment]
I'm not aware of anything.  As noted above, because BSC has hardforks that aren't based on Mainnet specs, `Common` won't support it 100% out of the box though it theoretically shouldn't take too much effort to add in whatever additional fork/EIPs have been added on the BSC side.  This is a super simplistic example but #1527 details the changes required to add the last hardfork (Arrow Glacier) to the code base and could serve as a rough guide on how to proceed.
