### ISSUE TITLE
VM: add option for custom miner payments

### ISSUE THREAD

**Issue by jochem-brouwer** [ethereumjs/ethereumjs-monorepo#1707]
Currently miners are paid in block/uncle rewards + tx fees in the currency used in the protocol (Ethereum). There are chains (?) which have a different payment mechanism (such as paying either in base fee or in tokens (?)). It would be nice to add an option to add specific payment logic for these chains, such that these chains can use our VM but use a different "miner" payment method.

**Comment by holgerd77** [comment]
Some context: this would mean to override the [assignBlockRewards()](https://github.com/ethereumjs/ethereumjs-monorepo/blob/master/packages/vm/src/runBlock.ts#L295) method in `VM.runBlock()`.

Just to mention: since this is also part of the consensus logic, we might or might not be able (want to) put this in a broader consensus context, thinking along the lines of #1044 e.g..

We might also want to think about renaming the above function to something more generic and generally go a bit more generic in the semantics, something like `consensusStateUpdatePoW()` e.g. and then call a `runBlock()` (or VM?) option `overrideBlockConsensus()` or the like.

Not sure, just some first thoughts on this to help this to enfold and get more concrete.

**Comment by holgerd77** [comment]
No follow-up, will close.
