### ISSUE TITLE
inconsistency between commonjs and import type statement and ethash construction issue

### ISSUE THREAD

**Issue by startgeek** [ethereumjs/ethereumjs-monorepo#1726]
hello there

following the instructions provided  you can't really mix import (module) statement and commonjs 

import Ethash from '@ethereumjs/ethash'
import { Block } from '@ethereumjs/block'
const level = require('level-mem');

when I convert all of these to import statement and add "type": "module" to my package.json file I get this error

const ethash = new Ethash(cacheDB)

Ethash is not a constructor (which it is there is a constructor object in Class)

**Comment by ryanio** [comment]
We are working on esmodules support but it won't be ready until typescript officially releases support (it is currently under their nightly releases). To fix this issue for now, please enable "esModuleInterop" in your tsconfig compilerOptions.

**Comment by holgerd77** [comment]
Still not getting through this whole topic TBH. So if the above is related (as well) to the default exports (sound a bit like it if Block works and Ethash does not), couldn't/shouldn't we just remove them in the next round of breaking releases anyhow - independently from any esmodules support - to give some ease on the situation? 🤔

Guess this wouldn't hurt anyone?

(specifically here: if we do I think it would also be ok to include ethash into the realm of breaking releases?

Respectively: would we need breaking releases anyhow? Or could we add named export additionally and just deprecate the old one? Not sure how we settled on the wallet library discussion right now.)

**Comment by ryanio** [comment]
This issue is not related to default exports not being a working patten, it is people using `type: "module"` without understanding what it actually means or what it is doing under the hood. For more info read the doc for esModuleInterop: https://www.typescriptlang.org/tsconfig#esModuleInterop

We can solve this as soon as typescript officially releases esmodule support and we ship a dist.esm folder, or we can do sooner and just note that typescript may make changes while esm support in TS is still being finalized.

**Comment by ryanio** [comment]
closing this for now, as TS has officially released esm support and a PR will be incoming to the develop branch from me
