### ISSUE TITLE
Trie: Rebuild Documentation does not work (deletes most existing docs)

### ISSUE THREAD

**Issue by holgerd77** [ethereumjs/ethereumjs-monorepo#1779]
This shouldn't be a blocker for this round of releases (too much of a side functionality added and releases are relatively time critical), but when docs are rebuild for the trie library, close to all documentation is deleted and only `docs/README.md` is kept.

This doesn't seem right, so this should be examined and fixed (might also be a problem on other libraries).

**Comment by ryanio** [comment]
Hmmm, that is interesting, I was able to reproduce.

I took a look at `packages/trie/typedoc.js` and in there we have as part of `exclude`: `"src/**/!(secure|checkpointTrie|baseTrie|walkController).ts"` so that seems to be stopping all the docs from being generated since when I comment it out it works again 😄 so we should decide which of these we should re-enable - maybe `secure` and `checkpointTrie`?

**Comment by holgerd77** [comment]
If I am not mistaken I guess you are arguing from the wrong base assumption, so this `"src/**/!(secure|checkpointTrie|baseTrie|walkController).ts"` exclude was initially *meant* to be for excluding "everything *but* e.g. secure and checkpoint trie" and not the other way around.

So the question would rather be "How do we get the above *into* the docs without everything else" (e.g. the DB and Util stuff and the like).

**Comment by ryanio** [comment]
so if I remove that exclude directive, we get the following docs:

```
# merkle-patricia-tree

## Table of contents

### Classes

- [BaseTrie](classes/BaseTrie.md)
- [CheckpointTrie](classes/CheckpointTrie.md)
- [SecureTrie](classes/SecureTrie.md)
- [WalkController](classes/WalkController.md)
```

so perhaps they improved their logic to exclude private classes not part of the exported API, because I'm not seeing anything else (like db, task executor, read stream, verifyRangeProof, etc.). I'd cautiously say we can remove it for the next docs:build and keep a close eye on it. Maybe we should take a look at other package typedoc configs that have exclude directives like that, to make sure those docs are still generating well.

**Comment by holgerd77** [comment]
This should get some practical look and validation respectively examination before we close here. So someone should look at 2-3 libraries, rebuild docs, get into preview, see what it's generated, how it differs and if things are generally ok.

**Comment by holgerd77** [comment]
> @holgerd77 is this still an issue?

Didn't check for quite some time, but: likely. 🙂
