### ISSUE TITLE
Move types into common/util

### ISSUE THREAD

**Issue by jochem-brouwer** [ethereumjs/ethereumjs-monorepo#1979]
There are some places where the only reason a dependency is needed is because we need to import the type. These types should be moved into either common or util (since all (?) packages require those), such that we can remove this dependency.

**Comment by holgerd77** [comment]
This type doubling in the EVM is giving me a lot of headaches, since there is actually a lot of this exported (right now), also there are things like this - also relatively huge - state related interface doublings, so more or less the state manager interface.

We might really want to do this type consolidation here between Beta 1 and Final, otherwise we might run into an even more challening situation with people taking these types in directly and we need to make sure that everything stays aligned. Then we can better just completely move over to *one* location (e.g. also things like the BlockchainInterface and the StateManagerInterface).

Just to drop here. Eventually it makes sense to already start on this with a reference/first-round implementation which we do not need (want) to merge pre-Beta 1 but where we can already see if things align well.

I would still think a new `Common` `api.ts` file would make sense with interfaces like `EthereumJSStateManager`.

**Comment by holgerd77** [comment]
Have removed the "Urgent" label here.

**Comment by gabrocheleau** [comment]
Is this still an issue?
