### ISSUE TITLE
Evaluate dual `receiptRoot`/`receiptsRoot` usage in `blockHeaderFromRpc` method

### ISSUE THREAD

**Issue by gabrocheleau** [ethereumjs/ethereumjs-monorepo#2245]
There are instances in the repository where `receiptRoot` is (or can be) used instead of `receiptsRoot` in a JSON-RPC block ([example](https://github.com/ethereumjs/ethereumjs-monorepo/blob/master/packages/block/src/header-from-rpc.ts#L21)). From reading the [docs](https://ethereum.org/en/developers/docs/apis/json-rpc/#eth_getblockbyhash), it seems that only `receiptsRoot` is the valid one, and `receiptsRoot` is also used more frequently in our monorepo. 

Could be interesting to investigating if that dual usage is necessary (retro-compatibility?), and if not, consider removing `receiptRoot` option.

**Comment by holgerd77** [comment]
This is also in the result object of `VM.runBlock()` and (I guess only used) in VM -> Benchmarks.

I wonder if we would want to update here *all* monorepo occurrences *before* the final releases, since this is at the end breaking and at the same time a very small change towards the correct version?

Would be inclined to do so, especially since we could - e.g. for the RPC result - in the worst case just re-add the wrong flavor, so nothing to be lost here.

@gabrocheleau do you want to open a PR on this if others do not disagree?

**Comment by gabrocheleau** [comment]
Yeah, would make sense to get this done before the final release, will push a PR within a day or two
