### ISSUE TITLE
Consider making vm's `hardforkByTTD` non-optional

### ISSUE THREAD

**Issue by gabrocheleau** [ethereumjs/ethereumjs-monorepo#2260]
In `vm.ts` this field is marked as optional, but it looks to me that it is always being set? I think we can improve here by making that field non-optional?

_Originally posted by @jochem-brouwer in https://github.com/ethereumjs/ethereumjs-monorepo/pull/2248#discussion_r958042755_

**Comment by jochem-brouwer** [comment]
I've checked, cannot infer that it is non-optional because `toType(undefined, TypeOutput.BigInt)` returns `undefined`. Plus, we do not want to default it to a number, because then each time when we try to set the hardfork, it will feed this number into common where it will do the difficulty check, i.e. if merge happened. Will close.
