### ISSUE TITLE
Ganache needs to support Kovan until October 5th. Can you help us add support back in?

### ISSUE THREAD

**Issue by davidmurdoch** [ethereumjs/ethereumjs-monorepo#2286]

**Comment by holgerd77** [comment]
Hi there, ah, yes, we removed Kovan here https://github.com/ethereumjs/ethereumjs-monorepo/issues/2286 since we decided it is time.

It should be relatively easy to re-integrate with the custom chain feature, so you can take the [Kovan JSON chain file](https://github.com/ethereumjs/ethereumjs-monorepo/pull/2206/files#diff-7b016833ada6c69c33108a52e49f033d1aaf9f08ee3b7018c613990afd9551b0) and initialize Common with the [customChainsArray](https://github.com/ethereumjs/ethereumjs-monorepo/tree/master/packages/common#initialize-using-customchains-array) option and pass in the Kovan JSON file.

If this is not working as expected it's a bug. 🙂

**Comment by holgerd77** [comment]
Hi @davidmurdoch, did you test this respectively is this a solution you can go with?

Feedback would be appreciated!

**Comment by davidmurdoch** [comment]
Thanks for the path forward and the follow up.

Ganache needs to keep supporting Node 12 until Truffle drops support for Node v12. A pre-requisite for Truffle dropping support for v12 is to fully support Node v18. and since EJS dropped Node 12 I've been doing the leg work to get Truffle updated to v18 so it can drop Node v12. Because we are getting so close to the October 5th Kovan support date and we haven't been able to finish up the EJS upgrade anyway (we are now working on getting EJS types rolled up into our build, since we Webpack almost everything), we've decided to forgo adding Kovan support back-in to Ganache. We plan on recommending for users that still need Kovan to use an older version of Ganache.

**Comment by jochem-brouwer** [comment]
Thanks for the update @davidmurdoch :smile:
