### ISSUE TITLE
Uncaught ReferenceError: Buffer is not defined

### ISSUE THREAD

**Issue by giorgi-abashidze** [ethereumjs/ethereumjs-monorepo#2312]
hello, i'm getting error: Uncaught ReferenceError: Buffer is not defined at eip1559Transaction.ts:29.
app is react js single page app using webpack and it is failing.

<img width="434" alt="Screenshot 2022-09-26 015519" src="https://user-images.githubusercontent.com/52792051/192167561-de742683-0dbc-4b07-b091-a091561b7719.png">

<img width="455" alt="Screenshot 2022-09-26 015537" src="https://user-images.githubusercontent.com/52792051/192167578-5e510da9-6b8f-4ba5-a211-d741fef4588f.png">

**Comment by acolytec3** [comment]
Are you using webpack 5? If so, you need to specify the `buffer` polyfill in your webpack config.

**Comment by acolytec3** [comment]
You can use this config for inspiration. https://github.com/ethereumjs/ultralight/blob/master/packages/browser-client/webpack.config.js

**Comment by giorgi-abashidze** [comment]
> Are you using webpack 5? If so, you need to specify the `buffer` polyfill in your webpack config.

so its a react thing? i'm not pro at react

**Comment by acolytec3** [comment]
Are you using `create-react-app`?

**Comment by giorgi-abashidze** [comment]
> Are you using `create-react-app`?

yes

**Comment by giorgi-abashidze** [comment]
and there is no webpack.config.js

**Comment by acolytec3** [comment]
Ah, okay. I haven't worked with CRA in a while. I'll have to spin up a new project and see what it needs. What command did you just to bootstrap your project? I'll see if I can recreate the issue and troubleshoot it. CRA might have changed since I last looked at it

**Comment by giorgi-abashidze** [comment]
> Ah, okay. I haven't worked with CRA in a while. I'll have to spin up a new project and see what it needs. What command did you just to bootstrap your project? I'll see if I can recreate the issue and troubleshoot it. CRA might have changed since I last looked at it

npx create-react-app appname

**Comment by acolytec3** [comment]
Cool, will take a look and see if I can find a fix for you

**Comment by giorgi-abashidze** [comment]
> Cool, will take a look and see if I can find a fix for you

ok, error uccurs after you import "import { ethTx } from '@ethereumjs/tx'" and trying instantiate like: ethTx.fromTxData(transactionRequest);

**Comment by acolytec3** [comment]
[Here's](https://github.com/acolytec3/CRA_Ethjs_Starter) a minimally configured CRA bootstrapped react app that will at least work with the `@ethereumjs/tx` library.

Unfortunately `@ethereumjs` libraries will not work with `create-react-app` out of the box because we currently use `buffer` and other Nodejs modules that require polyfills to work in browser. CRA v5 uses webpack v5 which doesn't automatically bundle nodejs polyfills. Since CRA offers no access to the webpack configuration, this repo uses a module called `craco` that allows you to extend/override bits of the CRA configuration without completely throwing it away but `craco` currently only supports CRA v4 on their master branch so I'm using the latest alpha release from their next version which does support CRA v5.  So, it's significantly less than ideal and I expect this setup to break at some point but it will get you started for now.  If you want to build a serious React app and leverage ethereumjs libraries, I suspect you'll have to go to a custom webpack setup similarly to what I linked at the top of this thread.  When we were building the Ultralight react app, we started on a similar setup to the starter repo I just configured and it got more and more unwieldy to maintain overtime so we switched to our own webpack setup which was harder to setup on the frontend but works with minimal maintenance at this point.

I'm sorry I don't have a simpler solution for you at this point but I think this is about as good as I can offer.

**Comment by acolytec3** [comment]
Also, if you do decide to use this starter template, lemme know how it goes.  There are possibly other polyfills I'm not thinking of (depending on which other libraries from our monorepo you use) so happy to take a quick look if something else breaks.

**Comment by giorgi-abashidze** [comment]
okay, thanks. I will give a try

**Comment by acolytec3** [comment]
Just checking in.  Did this resolve your issue?

**Comment by giorgi-abashidze** [comment]
> Just checking in. Did this resolve your issue?

@acolytec3 I can't manage using polyfills in create react app... I will close this issue because i'm not actively trying to find the right way.
Unfortunately I don't have a time for it.

**Comment by acolytec3** [comment]
Understood. Let me know if you have more questions down the line.
