### ISSUE TITLE
Missing Arbitrum mainnet in CustomChain enum

### ISSUE THREAD

**Issue by Cussone** [ethereumjs/ethereumjs-monorepo#2422]
Couldn't find the open issue, is there a plan to add Arbitrum to CustomChain enum? I see there is a testnet, but not the actual chain.

**Comment by holgerd77** [comment]
Hi there, this doesn't really need a plan since it is a total no-brainer, it's just that no one noted until now. 😋

Would you want to open a short PR on this? So this would need small additions to `common.ts` and `enum.ts` I guess.

Gold standard would then be if you would/could then *use* the modified Common and send a real-world test tx analog to https://github.com/ethereumjs/ethereumjs-monorepo/tree/master/packages/tx#sending-a-transaction and - if this works - add an entry to the tx docs as well linking to this issue. 🙂

**Comment by Cussone** [comment]
Hey @holgerd77, thank you for the quick response.

I've just created a PR [#2426](https://github.com/ethereumjs/ethereumjs-monorepo/pull/2426). Did a real-world test successfully. Please, tell me if anything else is needed from my side. 😃

**Comment by holgerd77** [comment]
Closed by #2426
