### ISSUE TITLE
Error - ChainId does not match common - NodeJS

### ISSUE THREAD

**Issue by rajesh1158** [ethereumjs/ethereumjs-monorepo#2429]
In NodeJS environment (v16.16.0, npm v8.11.0), when I interact with the Polygon mumbai chain, I get the error `The chain ID does not match the chain ID of Common`. On further debugging, I figured out that the original typescript source code gets converted to commonjs code for nodejs to run, and the `chainId()` function of common class does not return a BigInt but it returns a Number. Below is the exact source of error:

    FeeMarketEIP1559Transaction._getCommon (/project/node_modules/@ethereumjs/tx/dist/baseTransaction.js:236

I am passing common data as below:

    Common.custom('polygon-mumbai', {hardfork: 'london'})

Even if I pass below data as common, I still get the same issue:

    Common.custom({chainId: BigInt(80001)}, {hardfork: 'london'})

Please help!

**Comment by holgerd77** [comment]
Hi there, thanks for reporting! Might very well be that there is some BigInt/Number related bug in the code triggered by some special BigInt/Number input combination and/or library usage.

I am still stumbling a bit upon this sentence you wrote ` I figured out that the original typescript source code gets converted to commonjs code for nodejs to run, and the chainId() function of common class does not return a BigInt but it returns a Number.`, since I can't really imagine that after TS -> JS conversion `chainId()` would return another datatype? 🤔

Maybe it is a library version combination problem, since the old Common library version *would* actually return a `number` instead? Can your post your installed Common and Tx library versions here? Eventually you can also directly go into the Common code in your `node_modules` folder and post the code of the `chainId()` method here? That would be helpful!

Also helpful would eventually be if you could post the full stack trace around `FeeMarketEIP1559Transaction._getCommon (/project/node_modules/@ethereumjs/tx/dist/baseTransaction.js:236` and not just this single line.

Thanks! 🙂

**Comment by rajesh1158** [comment]
Hi @holgerd77. Thanks for reaching out. Below is the function chainId() from node_modules/@ethereumjs/common/dist/index.js:

    chainId() {
        return (0, ethereumjs_util_1.toType)(this.chainIdBN(), ethereumjs_util_1.TypeOutput.Number);
    }

Clearly, the output type is a Number and not a BigInt.

**Comment by rajesh1158** [comment]
The ethereumjs/tx version is `@ethereumjs/tx": "^4.0.1`, and the common package dependency version used by tx package.json is `^3.0.1`.

**Comment by rajesh1158** [comment]
Can anyone please guide me on this?

**Comment by acolytec3** [comment]
Can you provide an example repo where we can recreate this issue? I'm not able to identify a root cause just from your description as your code snippets all looks correct on first glance.

**Comment by acolytec3** [comment]
Given there has been no response. Will closer this here. Feel free to reopen as needed.
