### ISSUE TITLE
field.replaceAll is not a function error with recent versions

### ISSUE THREAD

**Issue by Aniket-Engg** [ethereumjs/ethereumjs-monorepo#2554]
```
        .replaceAll(/[^0-z]/g, "")
         ^

TypeError: field.replaceAll is not a function
    at Object.snake (remix-project/dist/libs/remix-tests/node_modules/@chainsafe/ssz/lib/util/strings.js:7:10)
    at Object.eth2 (remix-project/dist/libs/remix-tests/node_modules/@chainsafe/ssz/lib/util/strings.js:28:35)
    at precomputeJsonKey (remix-project/dist/libs/remix-tests/node_modules/@chainsafe/ssz/lib/type/container.js:409:40)
    at new ContainerType (remix-project/dist/libs/remix-tests/node_modules/@chainsafe/ssz/lib/type/container.js:32:26)
    at Object.<anonymous> (remix-project/dist/libs/remix-tests/node_modules/@ethereumjs/tx/node_modules/@ethereumjs/util/dist/ssz.js:9:22)
```
    
With recent ethereumjs/util v8.0.4, `@chainsafe/ssz` dep is added which shows above error. It can be specific to node.js 14

**Comment by holgerd77** [comment]
Hey @wemeetagain, do you know what is going on here? 🤔

Context is that we have now released a version of our libraries containing the [@chainsafe/ssz](https://github.com/ChainSafe/ssz/tree/master/packages/ssz) dependency for the first time (we have this in [@ethereumjs/util](https://github.com/ethereumjs/ethereumjs-monorepo/blob/master/packages/util/package.json) now to prepare for some SSZ withdrawal root functionality in the `@ethereumjs/block` library (which is still more or less unused, so in the worst case we could remove again for now).

So what happens here is that there is a `replaceAll()` call still in the library, which is ES2021 and therefore not compatible with Node 14 or many browsers. Looking at your library I see a build target of `ES2019` in the [package.json](https://github.com/ChainSafe/ssz/blob/master/tsconfig.build.json) file (or is this the wrong one?), so I wonder why there is still a `replaceAll()` (from [util/string.ts](https://github.com/ChainSafe/ssz/blob/master/packages/ssz/src/util/strings.ts#L6)) in the distributed package?

Not sure if it's possible for you guys to do short-term fixing releases here, I guess otherwise we need to take the library out of our dependencies again and deactivate the released functionality (which wouldn't be such a big deal right now, since the usage of this functionality is still somewhat away. We should then exchange though if the underlying eventual build target issue can be mitigated mid-term).

**Comment by Aniket-Engg** [comment]
@Aniket-Engg As we were planning a release and this thing came out, we are exploring a tentative fix. Still, would like to have more info to fix it permanently

**Comment by holgerd77** [comment]
We are on a fix, 80-95% work guarantee (PR in the works right now). I we can confirm we would release in the next 1-2 hours.

**Comment by holgerd77** [comment]
Ok, released, could you confirm that (hopefully) things work again?

**Comment by Aniket-Engg** [comment]
Yes, everything is fine again. Thank you so much for quick fix.
