### ISSUE TITLE
When restarting client on a PoW dev network, miner does not find a solution

### ISSUE THREAD

**Issue by jochem-brouwer** [ethereumjs/ethereumjs-monorepo#2614]
Steps:

- Start the client: `npm run client:start -- --dev=pow`
- Write down the private key and the address of the created account
- Ensure the client mines some blocks
- Stop the client
- Now restart the client with the account: `npm run client:start -- --dev=pow --unlock=<address of created  account>`
- The client will now not mine any new blocks, since ethash somehow does not find a solution

**Comment by jochem-brouwer** [comment]
Ok, I am starting to get more-and-more to be of favor to "just" deprectate PoW and thus close this one (we should shortly discuss on the call Wednesday)

**Comment by holgerd77** [comment]
I do not have the full picture how important this still is for dev networks. Yes, let's discuss shortly on the call, will add to the call notes.

**Comment by acolytec3** [comment]
Per our discussion on the team call, let's close this since we all agreed not to expend any unnecessary energy trying to solve obscure edge cases for `ethash` since PoW is deprecated from Ethereum so doesn't need any attention unless it breaks running a freshly started PoW chain (which may be useful on testnets/devnets in the near term)
