### ISSUE TITLE
Cannot find module 'node:crypto'

### ISSUE THREAD

**Issue by Aniket-Engg** [ethereumjs/ethereumjs-monorepo#2660]
Error comes while using `@ethereumjs/util`

Error details are:

```
/home/circleci/remix-project/dist/libs/remix-tests/node_modules/@noble/hashes/cryptoNode.js
- /home/circleci/remix-project/dist/libs/remix-tests/node_modules/@noble/hashes/utils.js
- /home/circleci/remix-project/dist/libs/remix-tests/node_modules/@noble/hashes/_sha2.js
- /home/circleci/remix-project/dist/libs/remix-tests/node_modules/@noble/hashes/sha256.js
- /home/circleci/remix-project/dist/libs/remix-tests/node_modules/@noble/curves/secp256k1.js
- /home/circleci/remix-project/dist/libs/remix-tests/node_modules/ethereum-cryptography/secp256k1.js
- /home/circleci/remix-project/dist/libs/remix-tests/node_modules/@ethereumjs/util/dist/constants.js
- /home/circleci/remix-project/dist/libs/remix-tests/node_modules/@ethereumjs/util/dist/index.js
- /home/circleci/remix-project/dist/libs/remix-tests/node_modules/@remix-project/remix-lib/src/util.js
- /home/circleci/remix-project/dist/libs/remix-tests/node_modules/@remix-project/remix-lib/src/index.js
- /home/circleci/remix-project/dist/libs/remix-tests/src/deployer.js
- /home/circleci/remix-project/dist/libs/remix-tests/src/runTestFiles.js
- /home/circleci/remix-project/dist/libs/remix-tests/src/run.js
- /home/circleci/remix-project/dist/libs/remix-tests/bin/remix-tests
```

Can be related to #2641

**Comment by acolytec3** [comment]
Can you provide guidance on how I can recreate this issue locally?  Is there an NPM script in the `remix-project` repo that will generate this result (and maybe a specific branch)?

**Comment by Aniket-Engg** [comment]
This is failing for Remix's master branch build. Issue is while using `remix-tests` library that is located here: https://github.com/ethereum/remix-project/tree/master/libs/remix-tests

**Comment by acolytec3** [comment]
Sorry, let me clarify my question.  I cloned the `remix-project` repo locally and ran `yarn` from the repository root to install all the dependencies followed by attempting to run `yarn build` and `yarn test` from the `lib/remix-tests` subdirectory and both fail with various unrelated errors that I'm not certain how to triage.  Can you provide specific steps needed to get to the point where I can run a test script or a test suite that will result in this error?  I'm not that familiar with remix so don't know specifically how to build everything in a way that will let me triage this issue.

**Comment by holgerd77** [comment]
//cc @paulmillr eventually

**Comment by paulmillr** [comment]
I have submitted a pull request to remix repository at https://github.com/ethereum/remix-project/pull/3648.

Remix CI is using node.js 14. In less than one week, the version will cease to be officially supported. Proof: https://github.com/nodejs/Release, https://endoflife.date/nodejs.

That means any project which still uses node.js 14 will have its security reduced. Since we're talking about ETH, a project will be putting users funds at risk.

This particular issue happened because [noble-hashes 1.3](https://github.com/paulmillr/noble-hashes/releases/tag/1.3.0) switched away from native node.js `crypto`, to webcrypto. Here's how it works now: https://github.com/paulmillr/noble-hashes/blob/5ee1bce1fe4d66c92f00c6a4c7623d6f8deed573/src/cryptoNode.ts#L1-L4. The change was done last month.

Why was the change necessary? Before, it was using node.js `crypto` functions - which was a) bringing many old, insecure, unaudited modules into user bundles; when bundlers shimmed crypto with `crypto-browserify` b) was not ESM-friendly c) had additional code branches. Now it unifies cryptographic operations into just webcrypto, which is supported in most environments such as deno, react native.

We have a couple options here.

1. Set Remix'es latest node.js-14-supported version to 0.32.1. Release 0.33.0 with new ethereumjs-util and ethereum-cryptography, targeting node.js 16, 18, 20.
2. Roll back noble-hashes behavior for an unknown amount of time, bringing back the bundler/esm issues. Release hashes 1.3.1, curves 1.0.1, ethereum-cryptography 2.0.1.

The main question here is for how long should node 14 be supported. I felt EOL date is a good deadline. After all, everyone who wants to keep using old node is still able to do this - with old versions of libraries. It's not like we're cutting off everyone by this decision.

**Comment by Aniket-Engg** [comment]
Thanks for all the details @paulmillr .

We are working to upgrade node version.

**Comment by Aniket-Engg** [comment]
FYI We moved to 20.0.0 . v16 was having issues. Thanks for your co-operation. Closing this.
