### ISSUE TITLE
v5.0.4 has no release or tag

### ISSUE THREAD

**Issue by TimDaub** [ethereumjs/ethereumjs-monorepo#2853]
https://github.com/ethereumjs/ethereumjs-monorepo/tags?after=%40ethereumjs%2Fcommon%403.1.2

can't find the commit that represents ethereumjs/trie v5.04, the version that I use lol

**Comment by jochem-brouwer** [comment]
Thanks for raising this issue.

I think the PR / commit you are looking for is this:

https://github.com/ethereumjs/ethereumjs-monorepo/pull/2556

(This commit: https://github.com/ethereumjs/ethereumjs-monorepo/commit/295e5a3caa69c226e8f8edfad4ea72a843bc0b4f )

**Comment by holgerd77** [comment]
Out of interest: is this a theoretical issue or do you really have a use for the commit? 🤔 I was always assuming I'm doing these GitHub releases only to "have a URL" for release notes, already thought about skipping this completely.

**Comment by TimDaub** [comment]
I tried using it to find precisely the code that I‘m using on GitHub, I ended up browsing 5.0.3 instead.

**Comment by TimDaub** [comment]
I‘m fine with a git tag on the right commit but yeah whatever

**Comment by holgerd77** [comment]
I have never done this manually to be honest.

So could I side-add this to another PR (so: add a tag) and then push this? 🤔

Maybe you can even write me down the exact git commands for this?

Would I then see this additional tag displayed somewhere in the PR?

**Comment by TimDaub** [comment]
- u find the commit hash that represents the version
- git checkout <hash>
- git tag v5.0.4
- git push —tags

I don‘t think I can do it because I think GH doesn‘t allow sending a PR for this

**Comment by holgerd77** [comment]
Ok, I was a bit shaky on this TBH (so the version you suggested e.g. is really *not* recommended, since `git push --tags` pushes *all* tags - did a quick google search - and this could pollute our whole monorepo if someone has a wrong tag set locally).

Anyhow: have now done with `git push origin '@ethereumjs/trie@5.0.4' --no-verify`

https://github.com/ethereumjs/ethereumjs-monorepo/tree/%40ethereumjs/trie%405.0.4
