### ISSUE TITLE
Reintroduce EVMInterface

### ISSUE THREAD

**Issue by holgerd77** [ethereumjs/ethereumjs-monorepo#2867]
@jochem-brouwer So we decided to re-introduce, right?

**Comment by jochem-brouwer** [comment]
Not sure here, I don't know what would be the use case of it, I have not yet seen anyone who wishes to use "their own" EVM instead of ours? :thinking:

**Comment by holgerd77** [comment]
That's not so much for people having their completely own EVM implementation but rather for users who maintain a fork of our library and pass this to the `VM` with the `evm` option. The moment they add a custom property for this or change some (non-called but publicly exposed) method name, things will break for them.

This can be avoided by keeping the interface (which would be an easy win).

Actually this is more or less the same argumentation we have for Blockchain or StateManager, where people (Hardhat e.g.) have their own modfied forks.

Side note: have you seen the comment here https://github.com/ethereumjs/ethereumjs-monorepo/pull/2866#discussion_r1254872876 ?

This would need a fix! 😆

**Comment by jochem-brouwer** [comment]
Ok, will re-introduce the interface :+1: :smile:

**Comment by jochem-brouwer** [comment]
I will create a PR tomorrow or Monday for this interface. However, the `EVMJournal` is now deeply integrated (`evm/journal.ts`) in EVM + VM. So this would add extra items to the EVM interface (it is not as shallow as it was in the past with only a few methods). Note: the original journal calls didn't go to EVM, they went to StateManager/EEI directly, but since we removed EEI now these methods have moved into EVM.

**Comment by jochem-brouwer** [comment]
Closed by #2869
