### ISSUE TITLE
Reconstructing a partial state `trie`

### ISSUE THREAD

**Issue by acolytec3** [ethereumjs/ethereumjs-monorepo#3178]
One question that has been raised in our Discord server recently was how to copy some or all of the state stored in the state manager's `trie` to another instance of the state manager.  This is different from the `shallowCopy` our API currently supports in that the way we would copy this state is to provide the EIP-1186 proofs provided by our `statemanager.getProof` to the State Manager and it would take the necessary steps to put these in the trie.  To this end, it would be nice to add a `fromProof` method on the `stateManager` similar to the `trie.fromProof` method that accepts an EIP-1186 proof and then inserts the account data into the account trie and constructs a storage trie from any storage proofs.  The gotcha here is the storage trie needs to be constructed by storing the nodes of the merkle storage proof directly in the DB as key/value pairs rather than using `trie.put` since our `statemanager` instantiates its underlying trie using hashed keys.

**Comment by jochem-brouwer** [comment]
To add:

`static` `fromProof(proof: Proof)` constructor in Trie. This setups a new trie where the first proof is dumped in. This also setups the root of the trie corresponding to that root. From here, `updateTrieFromProof(proof: Proof, safe?: boolean = false)` can be called on this new trie to add extra account proofs in. If `safe` is `true`, this also checks that the first node of the proof corresponds to the current root of the trie. This is `fromProof` (which we should deprecate) with an extra flag.

For `StateManager`, it should be possible to also add storage proof items. The condition that if one calls `StateManager.getProof` the trie should first be flushed should also be added (otherwise proofs with missing values are returned). It should be possible to use the returned `StateManager.getProof` to dump this into the state maanger, this thus instantiates also the storage tries corresponding to that proof.
