### ISSUE TITLE
Trace Equivalence for all Tests

### ISSUE THREAD

**Issue by jwasinger** [ethereumjs/ethereumjs-monorepo#351]
Using https://github.com/ethereum/evmlab , we can do trace equivalence testing between various EVM implementations (comparing each VM op-by-op).  This can expose faulty client behavior when client `B` has the right post state but different execution path than a reference client.

There are a lot of these failures last time I did a trace equivalence comparison of the state test suite between ethereumjs and geth.

**Comment by holgerd77** [comment]
Could you write a few lines here with a short introduction on where to start on the evmlab side and how to execute tests in this context? Am a bit lost here.

**Comment by s1na** [comment]
@holgerd77 I was thinking about something similar when trying to fix the broken tests. It'd really help clients debug if the test suite (optionally) came with a full trace of every test case. If that was the case, it'd be also possible to verify the trace and not only the post state root. Are you aware if something like this has been brought up?

Otherwise I'll try to see if I can get evmlab generate traces for geth and compare them manually.

**Comment by jwasinger** [comment]
Full traces of the test suite would be absolutely massive in size.  On the order of several gigabytes.

**Comment by s1na** [comment]
@holgerd77 Oh, I had totally missed that :sweat_smile: that'll be really handy, thanks

**Comment by rumkin** [comment]
@jwasinger It's possible to store only trace hashes, and use complete trace on demand for failing test only.

**Comment by holgerd77** [comment]
Will close in favor of #1215
