### ISSUE TITLE
Make state manager verifyProof functions standalone

### ISSUE THREAD

**Issue by scorbajio** [ethereumjs/ethereumjs-monorepo#3629]
The `verifyVerkleProof` function on the `StatelessVerkleStateManager` (SVSM) and `verifyProof` function on the `DefaultStateManager` (DSM) are candidates for extraction from the classes they are implemented on for tree shaking purposes. They are both pure functions and do not significantly access class state.

**Comment by holgerd77** [comment]
That's a complex beast, just had a closer look.

So the basic situation is that proof functionality is - atm - pretty divers along the different state managers, for MPT it's pretty extensive, various methods present, for verkle and RPC there is only one (?) method.

I think *if* we address we should either do for *all* proof functionality or none, otherwise things get too (even more) fragmented.

Since it is not realistic to align the functionality short-term (so: to fully have the same methods for all SM implementations) and so proof functionality is just bound to the specific SM anyhow (in contrast to the goal of having one unified interface), my suggestion would be to *then* just fully make this pretty explicit and do an additional subfolder `proofs` and put *all* proof methods from the different SMs there like:

- `proofs/merkle.ts` (We still should rename the `DefaultStateManager` -> `MerkleStateManager`, separate PR, but we can already align here)
- `proofs/verkle.ts`
- `proofs/rpc.ts`

Then we have the core state manager(s) code cleaned up and there remains only the code which has a generic interface and is interchangeable (for the most part).

The `StateManagerInterface` should then also reflect this and the `verifyVerkleProof` method there be removed (and instead have the checks for "is it a verkle SM" as in the `vmexecution.ts` client code file (`typeof this.vm.stateManager.initVerkleExecutionWitness === 'function'`).

Naming (for the extracted methods in the SM `proofs` folder is also a challenge, so that we do not mix up with the message from `trie` e.g.), I would cautiously suggest a scheme like `SM.verifyProof()` -> `verifyMerkleStateProof()`.

So: a lot to discuss, please do not act upon this immediately and rather let this stay a bit more, too much to get togehter here!

**Comment by scorbajio** [comment]
> That's a complex beast, just had a closer look.
> 
> So the basic situation is that proof functionality is - atm - pretty divers along the different state managers, for MPT it's pretty extensive, various methods present, for verkle and RPC there is only one (?) method.
> 
> I think _if_ we address we should either do for _all_ proof functionality or none, otherwise things get too (even more) fragmented.
> 
> Since it is not realistic to align the functionality short-term (so: to fully have the same methods for all SM implementations) and so proof functionality is just bound to the specific SM anyhow (in contrast to the goal of having one unified interface), my suggestion would be to _then_ just fully make this pretty explicit and do an additional subfolder `proofs` and put _all_ proof methods from the different SMs there like:
> 
>     * `proofs/merkle.ts` (We still should rename the `DefaultStateManager` -> `MerkleStateManager`, separate PR, but we can already align here)
> 
>     * `proofs/verkle.ts`
> 
>     * `proofs/rpc.ts`
> 
> 
> Then we have the core state manager(s) code cleaned up and there remains only the code which has a generic interface and is interchangeable (for the most part).
> 
> The `StateManagerInterface` should then also reflect this and the `verifyVerkleProof` method there be removed (and instead have the checks for "is it a verkle SM" as in the `vmexecution.ts` client code file (`typeof this.vm.stateManager.initVerkleExecutionWitness === 'function'`).
> 
> Naming (for the extracted methods in the SM `proofs` folder is also a challenge, so that we do not mix up with the message from `trie` e.g.), I would cautiously suggest a scheme like `SM.verifyProof()` -> `verifyMerkleStateProof()`.
> 
> So: a lot to discuss, please do not act upon this immediately and rather let this stay a bit more, too much to get togehter here!

This sounds right to me, the only part I'm not sure about is why would naming the functions or the files or directories for the state manager proof functions cause a mix up with `trie` messages?

**Comment by scorbajio** [comment]
The proof symbols being considered are the following:
`MerkleStateManager`:
* `getProof`
* `fromProof`
* `addStorageProof`
* `addProofData`
* `verifyProof`

`RPCStateManager`
* `accountExists`

`StatelessVerkleStateManager`
* `getProof`
* `verifyVerkleProof`

**Comment by holgerd77** [comment]
> I took a look, and it seems like the proof symbols being considered are the following:
> 
> `MerkleStateManager`:
> 
>     * `getProof` -> `getMerkleStateProof`
> 
>     * `fromProof` -> `fromMerkleStateProof`
> 
>     * `addStorageProof` -> `addMerkleStateStorageProof`
> 
>     * `addProofData` -> `addMerkleStateProofData`
> 
>     * `verifyMerkleProof` -> `verifyMerkleStateProof`
> 
> 
> `RPCStateManager`
> 
>     * `accountExists`: This function first fetches a proof for an account from the provider, then goes on to verify it, so we could break this function down into a getProof and verifyProof call in order to extract the proof function usage, or rename it to something like `verifyAccountProof` and extract it
> 
> 
> `StatelessVerkleStateManager`
> 
>     * `getProof` -> `getVerkleStateProof`
> 
>     * `verifyVerkleProof` -> `verifyVerkleStateProof`

Yeah, great summary, sounds all great, think we should do that! 🙂

**Comment by holgerd77** [comment]
Just for the complete task summary: do not forget to remove the proof methods (guess there is only one?) from the `StateManagerInterface` in `Common`. Last step though I guess.
