### ISSUE TITLE
StateManager: Rename `DefaultStateManager` -> `MerkleStateManager`

### ISSUE THREAD

**Issue by holgerd77** [ethereumjs/ethereumjs-monorepo#3631]
The default SM more and more looses its place with Verkle coming in and so being less and less the normal counted on case.

So we should rename here to `MerkleStateManager` to give this a more neutral stance.

(this is a bit inconsistent regarding the Stateless/Stateful stuff, I would nevertheless suggest to take in this small inconsistency and skip naming it `StatefulMerkleStateManager` for simplicity, since there will (likely ?) no `StatelessMerkleStateManager` anymore. No strong tendency though and happy to switch over if someone has some other preference)

The name of both the `src` and the `test` files should be adopted as well for consistency:

- `src/stateManager.ts` -> `src/merkleStateManager.ts`
- `test/stateManager.ts` -> test/merkleStateManager.spec.ts`

(not the `stateManager.account.spec.ts` like files I guess, I guess these should rather be made more generic as the `checkpoint.account.spec.ts` files, so iterating through the SMs like with `const SM of stateManagers`. This would actually be an important task as well, so that we have at least the verkle SMs better tested. Not 100% if possible/feasible though, might need a second look)

**Comment by scorbajio** [comment]
The `stateManager.spec.ts` test file and its variants (`stateManager.*.spec.ts`) all have tests that are relevant to more than just the `MerkleStateManager`. In #2980, I am currently using the same `for (const smType of stateManagers)` pattern to run the tests for the `FlatStateManager` that is currently under development, and I'd imagine other state managers (e.g. `SimpleStateManager`) could also be added in the same way, so that we are not keeping redundant tests for testing similar functionality on different state managers. We could potentially keep the name general for `stateManager.spec.ts` as well and move over to running the tests for multiple types of state managers.
