### ISSUE TITLE
PKCS#11 Support?

### ISSUE THREAD

**Issue by RNRetailer** [ethereumjs/ethereumjs-monorepo#3806]
Hi,

Someone forked your old code and added PKCS#11 support:

https://github.com/suenchunhui/ethereumjs-tx-pkcs11

Will you add support as well?

Thanks,
- Random Number Retailer LLC

**Comment by acolytec3** [comment]
@paulmillr any thoughts here?  Is this something that already exists in `@ethereumjs/wallet` or else could be easily supported?

**Comment by acolytec3** [comment]
Not disagreeing.  I was just asking if this was already included in the existing `wallet` implementation since I knew it supported various key formats.  This isn't an area I know a lot about so would need help understanding what PKCS#11 is and where it would be useful.  @RNRetailer, can you give more details on your use case?

**Comment by holgerd77** [comment]
Let’s close here.

**Comment by RNRetailer** [comment]
PKCS#11 support would allow users to use the NitroKey or similar devices to sign ETH transactions.

Given the security issues with the Ledger I think it is good to have alternatives.

Thanks
