### ISSUE TITLE
VM: Fixed-width BN / BigInt

### ISSUE THREAD

**Issue by s1na** [ethereumjs/ethereumjs-monorepo#470]
Most values used in the VM have a pre-specified width, and the EVM operates on 256 bit words. Built-in javascript numbers have 53 bits, which is not enough for most of the Ethereum values. As such, VM utilizes [bn.js](https://github.com/indutny/bn.js), which offers arbitrary-precision big numbers and operations on them.

`BN` is very convenient and works very well. The only downside is that validating the width of these numbers becomes paramount to ensure safety, and sometimes when the size hasn't been validated, an out-of-bound value can cause issues, e.g. see #464.

This issue was created to discuss solutions or alternatives to the current approach, and the requirements for any such solution.

One solution that I've seen is [fixed-bn.js](https://github.com/ewasm/fixed-bn.js), which is a wrapper over `bn.js`, that checks the width of value in its constructor. But it's very new, and it's missing some features, e.g. https://github.com/ewasm/fixed-bn.js/issues/6.

**Comment by s1na** [comment]
The current approach that [fixed-bn.js](https://github.com/ethereumjs/fixed-bn.js) takes is to simply wrap an arbitrary-precision bignum and do validations and modulo operations on top.

An alternative is to implement a pure fixed-precision bignum library (e.g. [intx (cpp)](https://github.com/chfast/intx) or [uint256 (go)](https://github.com/holiman/uint256)). Fixed-precision bignum has the benefits of `fixed-bn.js` but is expected to be more performant.

Downsides that I see are: Needs to be implemented from scratch either in pure JS (not sure how this would compare to native `BigInt`) or use a WebAssembly version. It's not as flexible as an arbitrary-precision bignum and it would need types for multiple variants, e.g. u64, u128, u256 (possibly bigger variants in future).

**Comment by gabrocheleau** [comment]
Since we are now migrating to BigInt, is this issue still relevant?

**Comment by acolytec3** [comment]
I guess it could be worth taking up at some point to decide if we need to add an overlay for fixed-width as it should be pretty feasiible.  Native Bigints offer the `BigInt.asUintN` and `BigInt.asIntN` constructor methods to define Bigints with a set width so shouldn't be too bad to implement if the team felt like we wanted to take that on.

**Comment by holgerd77** [comment]
@acolytec3 can you please take over this issue and decide if we want to close here or - if not - please open a new issue describing what we would then concretely want/plan to do? Thanks! 🙏

**Comment by acolytec3** [comment]
Are there any execution tests that cover edge cases with numbers that are too big and would cause overflow?  If so, (and if we are passing them), then this seems like a non-issue for now.  Otherwise, I will have to come up with one.

**Comment by holgerd77** [comment]
We/you could do this. But also to add another perspective: not all problems which are raised need to be fully solved. We can also simply decide that this is not biting us, neither right now nor in the last 5+ years, and we want to concentrate on other tasks and do not want to spend additional energy on this, not right now and not in the foreseable future. And therefore simply close here.

There are dozens of other things which would be "issues" and one could very well write them down. But there is a good reason not to do so, since otherwise one would get simply overwhelmed. At the end this whole list also has some good portion of arbitrary choice and randomness in it.

(so far on the "Philosophical Thursday" comments 😂 )

Or, to make it more practical again: @jochem-brouwer, since you worked on issues like #880 (solving the state overflow thing), would you think it is still worth to keep this open here as a dedicated issue? 🤔 

I would assume (but cannot ad-hoc prove) that these kind of cases *are* (mostly?) covered by cross-client tests.

What we can do is actually generally "internalize" this a bit more and just remind us to also think about these overflow cases as well, on times where we look into functionality where this might be an issue?

Does this make sense? (so that would be pledge to close, I personally do not think this issue is so helpful anymore)

**Comment by jochem-brouwer** [comment]
We actually had a discussion about this specific issue yesterday at the call, and it also came up why we would want this in the first place. I replied that this might also have to do with BN (fixed width for non-JS-native BigInts (remember when we used BN in the past :sweat_smile: - so nice that we can use native BigInts now) like BN could possibly also have a perfomance upgrade) but that it could also be there as an extra guard within the EVM to ensure we do not overflow.

Within the EVM all stack items are 32 bytes. In case of an addition operation which would end up at 33 or more bytes, the stack item would overflow and thus still stay at 32 bytes.

It is technically possible to get stack items larger than 32 bytes on stack, for instance funding an EOA with an insane amount of balance and then sending a tx with a `value` field larger than 32 bytes to a contract. Invoking `CALLVALUE` will then exceed EVMs 32 bytes. This is obviously not possible in practice.

I will close here, I don't see any benefit.
