### ISSUE TITLE
VM: Message and TxContext as interfaces

### ISSUE THREAD

**Issue by s1na** [ethereumjs/ethereumjs-monorepo#528]
The `Message` and `TxContext` class were created before the typescript migration to define a specific set of fields that the evm interpreter should operate on. However, they are more or less only data structures and have no functionality. This can be expressed now quite well as typescript interfaces.

Something that needs to be determined is how to handle optional fields and default values.

**Comment by holgerd77** [comment]
Can you do some labelling on opening issues?

**Comment by s1na** [comment]
Added, thanks for the reminder

**Comment by holgerd77** [comment]
Great, thanks

**Comment by alcuadrado** [comment]
> Something that needs to be determined is how to handle optional fields and default values.

I think this may enough to justify upgrading an interface into a class, but it's mostly a personal preference.

On the other side, the current implementation of those classes doesn't offer much value. In particular, `Message`'s constructor receives an object that it's almost exactly a `Message`.

**Comment by holgerd77** [comment]
Maybe this is worth a more detailed look as well.

**Comment by holgerd77** [comment]
(eventually this might also have some performance implications?)

**Comment by ryanio** [comment]
nice I wasn't aware of this issue, I like this idea.

TxContext doesn't have optional or default values so that should be able to be converted without a problem.

For Message, that's a good question. I searched a bit and one solution could be to define a defaultMessage obj with all the fallback values then use the spread operator when creating a message to fill in the missing values, e.g.: `const msg = { ...defaultMessage, msgValues }`

At the end of the day, I'm not sure if this is better or worse than doing `new Message(msgValues)` and have the class handle the fallback values. I almost prefer the simplicity of having the class do it in this case, but that's really the only thing the class is doing as OP suggests 😄

**Comment by gabrocheleau** [comment]
Like @ryanio mentioned in the last comment I'd also be inclined to keep the class for usage simplicity, but I think the constructor types+default values handling could easily be improved. 

TxContext could definitely be refactored to an interface since its constructor just returns the input values.

**Comment by gabrocheleau** [comment]
Resolved by #1892
