### ISSUE TITLE
Move generateCanonicalGenesis to runBlockchain

### ISSUE THREAD

**Issue by s1na** [ethereumjs/ethereumjs-monorepo#533]
`StateManager` only needs the `Common` object for generating the canonical genesis. `generateCanonicalGenesis` is only used in `runBlockchain` and I don't imagine it'd be really useful anywhere else. I wanted to propose we move the logic from `StateManager` and avoid passing `Common` to yet another class.

**Comment by holgerd77** [comment]
Makes very much sense. The genesis functionality was also very much in question when the ``StateManager`` was reworked. This might be the missing link for a finalized API here, would very much suggest that we take on this early on.

**Comment by holgerd77** [comment]
Some update here: `Common` is now also used in another context in `StateManager` (for `cleanupTouchedAccounts()`), so this change would not lead to being able to remove the `Common` class any more.

We might want to re-evaluate if we want to either drop or target this for a `v6` release (since breaking).

**Comment by holgerd77** [comment]
There has been some implementation tried out on this by @s1na  which was closed due to an unexpected level of complexity along the implementation. Will therefore close here, also considering the comment I made above.
