### ISSUE TITLE
`getStateRoot` throws on uncommitted checkpoints

### ISSUE THREAD

**Issue by s1na** [ethereumjs/ethereumjs-monorepo#567]
This has come up several times in the last week, e.g. in #563, #558 and also today raised by @iurimatias. Created this issue to give some thought to which `StateManager` methods should throw an error when there are uncommitted checkpoints, and which ones are okay, and whether we can find a way to solve this issue.

@holgerd77 do you remember from when `StateManager` was introduced what was the reasoning behind throwing in such cases?

**Comment by holgerd77** [comment]
Will forward the question to @mattdean-digicatapult (hi Matthew, how is it going? 😄 👋), who did the vast majority of the `StateManager` work back then.

**Comment by mattdean-digicatapult** [comment]
This is taking me back a bit. I'm inclined to think this was just for consistency within the `StateManager` interface. The change to make this `throw` was made late in the day as part of #393 which, as a documentation ticket, should only have made changes to make the new interface self-consistent. That said I have a vague recollection that something strange can happen if we flush the cache whilst the cache has uncommitted checkpoints, which is necessary in order to get the current state root.

The first question is whether we're happy to change the interface so that this doesn't throw? If so do we make that the default behaviour of the method, make it a separate method or make it a switch on this method? Whatever the decision if this behaviour is changed I would recommend some thorough testing to make sure this doesn't lead to strange behaviours when the cache is flushed.

**Comment by holgerd77** [comment]
Solved by #1209, will close.
