### ISSUE TITLE
Monorepo migration plan

### ISSUE THREAD

**Issue by evertonfraga** [ethereumjs/ethereumjs-monorepo#641]
This is a checklist that must be used during migration.

I am putting as many _operations_ in the migration script as possible, but there are still some things that can't be automated.

### Pre migration
- [x] Republish all ~144 releases to NPM with the new scoped structure, as a way to have historical releases in the scoped format.

### Automated migration
Migration can happen all at once, or per repository. 
- Script [here](https://github.com/evertonfraga/monorepify-ethereumjs/blob/master/monorepify.sh). 
- Project board [here](https://github.com/orgs/ethereumjs/projects/1)

### Post migration
- [x] Update project badges for each README.md found in the packages
- [x] ~Point all releases from `ethereumjs-vm` from the old tags (`v1.0.3`) to the new format (`@ethereumjs/vm@1.0.3`).~ Only then: 
  - [x] ~Delete all `vm` tags in the old format~ 
  - [x] ~Everyone that has push access to the repo should delete them locally, so they are not added back at a further point in the future~ 

### After dust settles
- [x] Deprecate old packages (`npm deprecate ethereumjs-account "ethereumjs-account is now @ethereumjs/account!"`)
- [x] Rename `ethereumjs-vm` to `ethereumjs-monorepo`. It creates automatic redirects for URL access, including `git fetch [...] ethereumjs-vm`. It also requires some more changes to the project URLs and documentation.

**Comment by holgerd77** [comment]
Some note: `ethereumjs-monorepo` is a too generic name - there will eventually also be other monorepos within the organization - we should postpone or leave renaming here until we come up with a better fitting description.

**Comment by ryanio** [comment]
Side note about husky, I found this, something to keep in mind: https://github.com/typicode/husky/blob/master/README.md#monorepos

**Comment by holgerd77** [comment]
Have deprecated the following packages on npm:

- [ethereumjs-vm](https://www.npmjs.com/package/ethereumjs-vm)
- [ethereumjs-block](https://www.npmjs.com/package/ethereumjs-block)
- [ethereumjs-blockchain](https://www.npmjs.com/package/ethereumjs-blockchain)
- [ethereumjs-common](https://www.npmjs.com/package/ethereumjs-common)
- [ethereumjs-devp2p](https://www.npmjs.com/package/ethereumjs-devp2p)
- [ethashjs](https://www.npmjs.com/package/ethashjs)
- [ethereumjs-tx](https://www.npmjs.com/package/ethereumjs-tx)

Will close this issue here.
