### ISSUE TITLE
PR Labeler doesn't seem to be working

### ISSUE THREAD

**Issue by evertonfraga** [ethereumjs/ethereumjs-monorepo#867]

**Comment by ryanio** [comment]
yes i had to disable it in #675 since it wasn't functioning properly, but it would be good to revisit

**Comment by holgerd77** [comment]
I will close this due to non-activity for close to a year for a very much "nice to have" thing where the need has not very much expressed again. Feel free to raise again if someone sees the need (I am generally ok with the manual labeling and find this sometimes more targeted for avoiding false positives (e.g. just some lint fix in library x where a label is not needed respectively just noise)).
